const fs=require('node:fs'),path=require('node:path');const artifactDir=process.env.TEST_ARTIFACTS || 'test-artifacts';fs.mkdirSync(artifactDir,{recursive:true});
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright'),assert=require('node:assert/strict');
const runtime=process.env.PLAYWRIGHT_EXECUTABLE;
(async()=>{
 const b=await chromium.launch({headless:true,...(runtime?{executablePath:runtime}:{})}),errors=[];
 const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});};
 const c=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),f=await c.newPage();watch(f);await f.goto((process.env.TEST_GAME_URL || 'http://127.0.0.1:8766'));await f.locator('#begin-game').tap();await f.locator('#character-builder').waitFor({state:'visible'});await f.waitForTimeout(250);assert(await f.evaluate(()=>document.fullscreenElement===document.documentElement),'Begin enters actual fullscreen');await f.locator('#mobile-fullscreen').tap();await f.waitForTimeout(100);assert(await f.evaluate(()=>!document.fullscreenElement),'Exit fullscreen');await f.locator('#mobile-fullscreen').tap();await f.waitForTimeout(100);assert(await f.evaluate(()=>!!document.fullscreenElement),'Fullscreen toggle re-enters');await c.close();
 console.log('Fullscreen entry, exit and re-entry passed.');
 const ctx=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await ctx.addInitScript(()=>{Element.prototype.requestFullscreen=undefined;Element.prototype.webkitRequestFullscreen=undefined;});const p=await ctx.newPage();watch(p);await p.goto((process.env.TEST_GAME_URL || 'http://127.0.0.1:8766'));await p.locator('#begin-game').tap();assert(await p.locator('#fullscreen-status').isVisible(),'Unsupported browser home-screen guidance');await p.evaluate(()=>document.getElementById('fullscreen-status').hidden=true);await p.locator('#equipment-item').selectOption('weapon-longsword');await p.locator('#equipment-add').tap();await p.locator('#finish-character').tap();await p.evaluate(()=>battleSystem.nextEncounterDistance=1e9);
 const reports=await p.evaluate(()=>{
  const c=gameUI.character,checks=[],ok=(x,m)=>{if(!x)throw Error(m);checks.push(m);},throws=(fn,m)=>{let yes=false;try{fn()}catch{yes=true}ok(yes,m)},find=n=>ALCHEMY_INGREDIENTS.find(i=>i.name===n).id;
  c.crafting.alchemy=5;c.crafting.smithing=6;c.attributes.wit=5;const kit=worldCrafting.objects.find(o=>o.id==='public-kit');worldCrafting.rental=c;player.x=kit.x+20-player.width/2;player.y=kit.y-player.height/2;player.center={x:kit.x+20,y:kit.y};worldCrafting.update(0);
  ok(worldCrafting.access(c).includes('kit'),'Brewing uses a real rented bench');
  const examples=[
   [['Aconite','Bloodmoss','Allspice Root','Bryonia'],['rare:lower attacks by 1 tn for 2 rounds against wounded enemies','uncommon:add 2 cp for 2 rounds while attacking'],5,5],
   [['Aconite','Arenaria','Allspice Root','Bryonia'],['uncommon:add 2 cp for 2 rounds while enemy is wounded','uncommon:add 2 cp for 2 rounds while attacking'],4,3],
   [['Balisse Fruit','Longrube',"Idunn's Apples",'Allspice Root'],['uncommon:add 2 cp for 2 rounds while unwounded','common:remove 3 fatigue','common:increase health by 1 for 2 rounds'],4,2],
   [['Arenaria','Bryonia','Honeysuckle'],['rare:ignore knockout for 2 rounds'],3,4]
  ];
  for(const[names,keys,slots,skill]of examples){const ids=names.map(find),formula=Crafting.formula(ids,keys,skill);ok(!formula.error&&formula.slots===slots,'PDF example '+names.join(' / ')+' valid');ok(Crafting.formula(ids,keys,skill-1).error,'Example skill requirement enforced');ids.forEach(id=>Crafting.add(c,id,ALCHEMY_INGREDIENTS.find(i=>i.id===id).name,4));c.conditions.fatigue=0;Crafting.brew(c,ids,keys,()=>.99);}
  const triplePotion=c.inventoryItems.filter(r=>r.potionEffects).at(-1);ok(triplePotion.potionEffects[0].duration===4,'Rare triplet has four rounds');Crafting.drink(c,triplePotion);for(let i=0;i<3;i++)Crafting.tick(c);ok(Crafting.has(c,'ignore knockout'),'Triplet survives three rounds');Crafting.tick(c);ok(!Crafting.has(c,'ignore knockout'),'Triplet expires on fourth round');
  ok(!Crafting.candidates([find('Allspice Root')]).length,'Singleton produces no effects');const ids=examples[0][0].map(find);ok(Crafting.formula([...ids,ids[0]],examples[0][1],5).error,'Duplicate ingredient rejected');ok(Crafting.formula([...ids,find('Ambrosia'),find('Aglaophotis')],examples[0][1],5).error,'Six ingredients rejected');const overIds=['Aconite','Aglaophotis','Allspice Root','Arenaria','Bryonia'].map(find),candidates=Crafting.candidates(overIds);ok(Crafting.formula(overIds,candidates.map(e=>e.key),5).error,'More than five slots rejected');
  c.conditions.fatigue=0;let qty=Crafting.count(c,ids[0]);Crafting.brew(c,ids,examples[0][1],()=>0);ok(Crafting.count(c,ids[0])===qty-1,'Failed brew consumes ingredients');
  const traitNames=ALCHEMY_INGREDIENTS.filter(i=>i.common==='increase health by 1 for 2 rounds').slice(0,3).map(i=>i.id),effect=Crafting.candidates(traitNames).find(e=>e.rarity==='common'),enhanced=Crafting.formula(traitNames,[effect.key],1,{[effect.key]:'potency'}).effects[0];ok(enhanced.text==='increase health by 2 for 2 rounds','Triplet potency improves health');const hp=c.conditions.maxHealth;const potion={id:'test-health',name:'Test',quantity:2,potionEffects:[enhanced]};c.inventoryItems.push(potion);Crafting.drink(c,potion);Crafting.drink(c,potion);ok(c.conditions.maxHealth===hp+2,'Health doses do not stack');Crafting.tick(c);Crafting.tick(c);ok(c.conditions.maxHealth===hp,'Enhanced health fully expires');
  const forge=worldCrafting.objects.find(o=>o.id==='public-forge');player.x=forge.x-20-player.width/2;player.y=forge.y-player.height/2;player.center={x:forge.x-20,y:forge.y};worldCrafting.update(0);c.conditions.fatigue=0;const shop=c.inventoryItems.find(r=>r.id==='weapon-longsword');shop.durability=5;Crafting.repair(c,shop.id,()=>.99);ok(shop.durability===10,'Purchased Standard weapon repairs');
  Crafting.add(c,'bar-carburized-carburized','Carburized bar',1,{material:'carburized',qualitySource:'carburized'});c.conditions.fatigue=0;Crafting.forge(c,'longsword','bar-carburized-carburized',['attack','defense'],()=>.99);const fine=c.inventoryItems.find(r=>r.baseWeapon&&r.quality==='Fine');ok(fine.improvements.length===1,'Fine quality improves one stat');fine.durability=5;c.conditions.fatigue=0;Crafting.repair(c,fine.id,()=>0);ok(fine.destroyed,'Failed repair destroys weapon');
  player.x=worldCrafting.camp.x-player.width/2;player.y=worldCrafting.camp.y-player.height/2;player.center={x:worldCrafting.camp.x,y:worldCrafting.camp.y};worldCrafting.rental=null;c.conditions.fatigue=0;qty=Crafting.count(c,ids[0]);throws(()=>Crafting.brew(c,ids,examples[0][1],()=>.99),'No remote brewing');ok(Crafting.count(c,ids[0])===qty,'Rejected remote work preserves ingredients');
  c.crafting.activeEffects=[];c.conditions.fatigue=0;return checks;
 });console.log(reports.join('\n'));
 await p.evaluate(()=>battleSystem.startBattle(4));await p.waitForTimeout(800);
 for(const size of [{width:390,height:844},{width:320,height:568},{width:844,height:390},{width:568,height:320},{width:768,height:1024}]){
  await p.setViewportSize(size);await p.waitForTimeout(100);await p.getByRole('tab',{name:'Actions',exact:true}).tap();
  const metrics=await p.evaluate(()=>{const s=document.querySelector('#battle-screen'),stage=s.querySelector('.battle-stage').getBoundingClientRect(),actors=[...s.querySelectorAll('.battle-actor')].map(e=>e.getBoundingClientRect().toJSON());return{width:innerWidth,height:innerHeight,docWidth:document.documentElement.scrollWidth,scroll:s.scrollHeight-s.clientHeight,stage:stage.toJSON(),actors};});
  assert(metrics.docWidth<=size.width+1);assert(metrics.scroll<=1,'Whole battle screen does not scroll');
  const resolve=await p.locator('#battle-resolve').boundingBox();assert(resolve.y>=0&&resolve.y+resolve.height<=size.height+1,'Resolve always visible');assert(resolve.height>=44);
  for(const a of metrics.actors){assert(a.x>=metrics.stage.x-1&&a.x+a.width<=metrics.stage.x+metrics.stage.width+1,'Actor fits horizontally');assert(a.y>=metrics.stage.y&&a.y+a.height<=metrics.stage.y+metrics.stage.height+1,'Actor fully visible');}
  for(const tab of ['Tactics','Status','Log','Actions']){await p.getByRole('tab',{name:tab,exact:true}).tap();assert(await p.locator(`[role=tabpanel].mobile-panel-active`).isVisible());assert((await p.locator('#battle-resolve').boundingBox()).y+resolve.height<=size.height+1);}
  await p.locator('#battle-inventory-open').tap();assert(await p.locator('#battle-inventory-popup').isVisible());await p.locator('#battle-inventory-close').tap();
  if(size.width===390)await p.screenshot({path:path.join(artifactDir,'mobile-combat-portrait.png'),scale:'css'});if(size.width===844)await p.screenshot({path:path.join(artifactDir,'mobile-combat-landscape.png'),scale:'css'});
  console.log(`Visible battlefield, actors, tab panels and fixed actions passed ${size.width}x${size.height}`);
 }
 await p.setViewportSize({width:390,height:844});await p.locator('#battle-resolve').tap();await p.waitForTimeout(1000);assert(await p.evaluate(()=>battleSystem.logElement?.children.length>0||document.getElementById('battle-log').children.length>0),'Resolve creates exchange log');
 const desk=await b.newPage({viewport:{width:1280,height:800}});watch(desk);await desk.goto((process.env.TEST_GAME_URL || 'http://127.0.0.1:8766'));assert(!await desk.locator('#mobile-fullscreen').isVisible());assert(!await desk.locator('#battle-screen').isVisible());await desk.keyboard.press('Space');await desk.locator('#equipment-item').selectOption('weapon-longsword');await desk.locator('#equipment-add').click();await desk.locator('#finish-character').click();await desk.evaluate(()=>battleSystem.startBattle(2));assert(!await desk.locator('.mobile-battle-tabs').isVisible());assert(await desk.locator('.battle-controls #battle-stance').isVisible());assert(await desk.locator('.battle-controls #battle-resolve').isVisible());console.log('Desktop combat keeps all original controls.');
 assert.equal(errors.length,0,JSON.stringify(errors));await b.close();console.log('No script or asset errors.');
})().catch(e=>{console.error(e);process.exit(1)});
