const fs=require('node:fs'),path=require('node:path');const artifactDir=process.env.TEST_ARTIFACTS || 'test-artifacts';fs.mkdirSync(artifactDir,{recursive:true});
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE}:{})}),p=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.TEST_GAME_URL || 'http://127.0.0.1:8766'));await p.locator('#begin-game').tap();await p.locator('#equipment-item').selectOption('weapon-longsword');await p.locator('#equipment-add').tap();await p.locator('#finish-character').tap();await p.evaluate(()=>{const c=gameUI.character,o=worldCrafting.objects.find(o=>o.id==='public-kit');battleSystem.nextEncounterDistance=1e9;worldCrafting.rental=c;player.x=o.x+20-player.width/2;player.y=o.y-player.height/2;player.center={x:o.x+20,y:o.y};worldCrafting.update();c.crafting.alchemy=5;c.conditions.fatigue=0;ALCHEMY_INGREDIENTS.forEach(i=>Crafting.add(c,i.id,i.name,5));gameUI.openCharacterMenu();});await p.getByRole('tab',{name:'Crafting',exact:true}).tap();await p.getByText('Recipes from your alchemy examples',{exact:true}).tap();const recipes=p.locator('.craft-history').filter({hasText:'Recipes from your alchemy examples'});for(let index=0;index<4;index++){await recipes.locator('button').nth(index).tap();assert(await p.getByText(/Legal formula/).isVisible());await p.getByText('Recipes from your alchemy examples',{exact:true}).tap();}
 await p.getByRole('button',{name:'Brew potion',exact:true}).scrollIntoViewIfNeeded();await p.evaluate(()=>{window.realCraftRandom=Math.random;Math.random=()=>.99;});await p.getByRole('button',{name:'Brew potion',exact:true}).tap();await p.evaluate(()=>{Math.random=window.realCraftRandom;});assert(await p.evaluate(()=>gameUI.character.inventoryItems.some(r=>r.potionEffects?.some(e=>e.text==='ignore knockout for 4 rounds'))),'UI brews four-round example');
 await p.getByText('Recipes from your alchemy examples',{exact:true}).tap();await recipes.locator('button').nth(2).tap();
 // Add a third carried matching health ingredient to expose the potency selector.
 await p.evaluate(()=>{const extra=ALCHEMY_INGREDIENTS.find(i=>i.common==='increase health by 1 for 2 rounds'&&!gameUI.brewIngredients.includes(i.id));gameUI.brewIngredients.push(extra.id);gameUI.renderCharacterSheet();});await p.getByRole('combobox',{name:'Triplet bonus: increase health by 1 for 2 rounds',exact:true}).selectOption('potency');assert(await p.getByText('increase health by 2 for 2 rounds',{exact:true}).isVisible());await p.screenshot({path:path.join(artifactDir,'alchemy-triplet-selection.png'),scale:'css'});
 await p.getByRole('button',{name:'Return to world',exact:true}).tap();const character=await p.locator('#touch-character').boundingBox(),interact=await p.locator('#touch-interact').boundingBox();assert(character.x<interact.x&&character.y<interact.y,'Character and Interact swap both positions');await p.screenshot({path:path.join(artifactDir,'mobile-swapped-controls.png'),scale:'css'});
 assert.equal(errors.length,0,errors.join('\n'));console.log('All four recipe presets, real UI brewing, triplet potency selector and swapped touch controls passed.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
