const fs=require('node:fs'),path=require('node:path');const artifacts=process.env.TEST_ARTIFACTS||'test-artifacts';fs.mkdirSync(artifacts,{recursive:true});
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE}:{})}),ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_GAME_URL||'http://127.0.0.1:8766');await p.locator('#begin-game').tap();await p.locator('#equipment-item').selectOption('weapon-longsword');await p.locator('#equipment-add').tap();await p.locator('#finish-character').tap();await p.evaluate(()=>battleSystem.nextEncounterDistance=1e9);
 const l=p.locator('#touch-select'),r=p.locator('#touch-start'),a=p.locator('#touch-interact'),back=p.locator('#touch-character');assert.equal(await a.innerText(),'A');assert.equal(await back.innerText(),'B');assert(await back.isDisabled());const lb=await l.boundingBox(),rb=await r.boundingBox();assert(lb.x<50&&rb.x>280&&lb.y<30&&rb.y<30);
 await l.tap();assert(await p.locator('#character-menu').isVisible());assert(await p.evaluate(()=>gameUI.activeSheetTab==='character'));assert(!await a.isVisible());assert(!await p.locator('.touch-dpad').isVisible());const paused=await p.evaluate(()=>({x:player.x,y:player.y,travel:battleSystem.distanceTravelled}));await p.waitForTimeout(200);assert.deepEqual(await p.evaluate(()=>({x:player.x,y:player.y,travel:battleSystem.distanceTravelled})),paused);await back.tap();assert(await p.evaluate(()=>gameUI.isMapActive()));
 await r.tap();assert.equal(await p.locator('#mobile-sheet-section').inputValue(),'browserSaves');const slot=p.locator('[data-sheet-panel=browserSaves] .save-slot-row').first();await slot.getByRole('button',{name:'Save',exact:true}).tap();const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('tros-browser-save-1')));assert(saved.character.name);await back.tap();await p.evaluate(()=>{gameUI.character.wealthTotal=1;gameUI.persistCharacter();});await r.tap();await slot.getByRole('button',{name:'Load',exact:true}).tap();assert(await p.evaluate(()=>gameUI.isMapActive()));assert.equal(await p.evaluate(()=>gameUI.character.wealthTotal),saved.character.wealthTotal);
 await r.tap();await p.locator('#mobile-sheet-section').selectOption('exportSaves');const exportSlot=p.locator('[data-sheet-panel=exportSaves] .save-slot-row').first(),download=p.waitForEvent('download');await exportSlot.getByRole('button',{name:'Export',exact:true}).tap();assert((await download).suggestedFilename().endsWith('.json'));await exportSlot.locator('input[type=file]').setInputFiles({name:'imported.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...saved,character:{...saved.character,name:'Imported Hero'}}))});await p.getByText('imported.json imported into slot 1.',{exact:true}).waitFor();await exportSlot.getByRole('button',{name:'Load',exact:true}).tap();assert.equal(await p.evaluate(()=>gameUI.character.name),'Imported Hero');
 await p.evaluate(()=>{const s=worldCrafting.smith;player.x=s.x-player.width/2;player.y=s.y+16-player.height/2;player.center={x:s.x,y:s.y+16};worldCrafting.update();});await a.tap();assert(await p.getByRole('dialog',{name:'Village Smith'}).isVisible());await back.tap();assert(!await p.getByRole('dialog',{name:'Village Smith'}).isVisible());
 await p.evaluate(()=>{const c=gameUI.character,kit=worldCrafting.objects.find(o=>o.id==='public-kit');worldCrafting.rental=c;player.x=kit.x+20-player.width/2;player.y=kit.y-player.height/2;player.center={x:kit.x+20,y:kit.y};worldCrafting.update();c.crafting.alchemy=5;c.conditions.fatigue=0;ALCHEMY_INGREDIENTS.slice(0,12).forEach(i=>Crafting.add(c,i.id,i.name,2));});
 for(const size of [{width:390,height:844},{width:320,height:568},{width:844,height:390},{width:568,height:320},{width:768,height:1024}]){await p.setViewportSize(size);await l.tap();const choose=p.locator('#mobile-sheet-section');await choose.selectOption('attributes');assert(!await p.locator('#character-sheet-tabs').isVisible());const layout=await p.locator('[data-sheet-panel=attributes]').evaluate(el=>({columns:getComputedStyle(el).gridTemplateColumns.split(' ').length,width:el.scrollWidth,client:el.clientWidth}));assert(layout.columns>=2);assert(layout.width<=layout.client+1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(size.width===390)await p.screenshot({path:path.join(artifacts,'mobile-character-compact.png'),scale:'css'});
  await choose.selectOption('crafting');await p.getByRole('combobox',{name:'Craft',exact:true}).selectOption('alchemy');await p.getByRole('combobox',{name:'Brewing step',exact:true}).selectOption('ingredients');assert(await p.locator('.ingredient-shelf').isVisible());assert(!await p.locator('.brew-preview').isVisible());await p.getByRole('button',{name:'Review potion effects',exact:true}).tap();assert(await p.locator('.brew-preview').isVisible());assert(!await p.locator('.ingredient-shelf').isVisible());
  await p.getByRole('combobox',{name:'Craft',exact:true}).selectOption('smithing');await p.getByRole('combobox',{name:'Smithing task',exact:true}).selectOption('refine');await p.getByRole('combobox',{name:'Metal recipe',exact:true}).selectOption('4');assert.equal(await p.locator('.mobile-smith-layout .recipe-row:visible').count(),1);assert(await p.locator('.recipe-row:visible').getByText('Blister Steel Bar',{exact:true}).isVisible());await p.getByRole('combobox',{name:'Smithing task',exact:true}).selectOption('forge');assert(await p.getByText('Ⅱ Forge weapon',{exact:true}).isVisible());assert(!await p.getByText('Ⅰ Refine metal',{exact:true}).isVisible());if(size.width===844)await p.screenshot({path:path.join(artifacts,'mobile-smithing-compact.png'),scale:'css'});await p.getByRole('combobox',{name:'Smithing task',exact:true}).selectOption('repair');assert(await p.getByText('Ⅲ Repair & equip',{exact:true}).isVisible());await back.tap();assert(await p.evaluate(()=>gameUI.isMapActive()));console.log(`Compact character/crafting menus, dropdowns and touch back passed ${size.width}x${size.height}`);
 }
 await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(artifacts,'mobile-ab-lr-controls.png'),scale:'css'});await p.evaluate(()=>battleSystem.startBattle(1));assert(!await l.isVisible());await p.locator('#battle-inventory-open').tap();assert(await back.isVisible());await back.tap();assert(!await p.locator('#battle-inventory-popup').isVisible());
 const desk=await b.newPage({viewport:{width:1280,height:800}});await desk.goto(process.env.TEST_GAME_URL||'http://127.0.0.1:8766');await desk.keyboard.press('Space');await desk.locator('#equipment-item').selectOption('weapon-longsword');await desk.locator('#equipment-add').click();await desk.locator('#finish-character').click();await desk.keyboard.press('c');assert(await desk.getByRole('tab',{name:'Character',exact:true}).isVisible());assert(!await desk.locator('#mobile-sheet-section').isVisible());assert(!await desk.locator('#touch-select').isVisible());assert.equal(errors.length,0,JSON.stringify(errors));console.log('A interacts; B closes world, character and battle inventory windows; L/R pause/toggle screens; save/load, export/import, desktop navigation and no script errors passed.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
