const fs=require('node:fs'),path=require('node:path');const artifacts=process.env.TEST_ARTIFACTS||'test-artifacts';fs.mkdirSync(artifacts,{recursive:true});
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE}:{})}),page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});await page.goto(process.env.TEST_GAME_URL||'http://127.0.0.1:8766');await page.keyboard.press('Space');await page.locator('#equipment-item').selectOption('weapon-longsword');await page.locator('#equipment-add').click();await page.locator('#finish-character').click();await page.evaluate(()=>{battleSystem.nextEncounterDistance=1e9;gameUI.character.wealthTotal=1000;});await page.waitForTimeout(300);
 const checks=await page.evaluate(()=>{
  const c=gameUI.character,out=[],ok=(yes,msg)=>{if(!yes)throw Error(msg);out.push(msg);},throws=(fn,msg)=>{let yes=false;try{fn()}catch{yes=true}ok(yes,msg);},placeBy=o=>{for(const[dx,dy]of[[20,0],[-20,0],[0,20],[0,-20],[16,16],[-16,16]]){player.x=o.x+dx-player.width/2;player.y=o.y+dy-player.height/2;player.center={x:player.x+player.width/2,y:player.y+player.height/2};worldCrafting.update();if(worldCrafting.nearby()?.id===o.id&&!collisionBlocks.concat(worldCrafting.getCollisionBlocks()).some(b=>Camping.overlap({x:player.x,y:player.y,width:player.width,height:player.height},b)))return;}throw Error('No accessible approach to '+o.id); };
  ok(Camping.objects().filter(o=>o.kind==='storage').length===1,'Starter tent has a physical storage box');const box=Camping.objects().find(o=>o.kind==='storage');ok(Math.hypot(box.x-worldCrafting.camp.x,box.y-worldCrafting.camp.y)<=90,'Storage box is beside starter tent');
  const fake={...c,attributes:{...c.attributes,strength:4,endurance:4},inventoryItems:[{id:'test-load',quantity:1,weight:24}],armor:{poolPenalty:0},giftsFlaws:[]};ok(InventoryLoad.stats(fake).capacity===125,'Strength 4 carrying limit is 125 lb');for(const[weight,penalty]of[[24,0],[24.1,1],[40,1],[40.1,2],[80,2],[80.1,3],[160,3],[160.1,5]]){fake.inventoryItems[0].weight=weight;ok(InventoryLoad.stats(fake).fatiguePenalty===penalty,`Companion fatigue boundary ${weight} lb: ${penalty}`);}
  const before=Crafting.count(c,'raw-stone');throws(()=>Crafting.add(c,'raw-stone','Stone',100),'Over-capacity resource addition rejected');ok(Crafting.count(c,'raw-stone')===before,'Rejected pickup does not add items');
  for(const id of Object.keys(CAMP_ITEMS))Camping.buy(id);ok(Object.keys(CAMP_ITEMS).every(id=>Crafting.count(c,id)===1),'Tent, fire pit and box are purchasable inventory items');const cash=c.wealthTotal;throws(()=>{const old=c.attributes.strength;c.attributes.strength=1;try{Crafting.add(c,'raw-stone','Stone',9);Camping.buy('gear-tent');}finally{c.attributes.strength=old}},'Capacity is enforced before further purchases');ok(c.wealthTotal===cash,'Failed capacity operation does not spend money');
  Crafting.add(c,'raw-wood','Wood',5);placeBy(box);const q=Crafting.count(c,'raw-wood');Camping.transfer(box,'store','raw-wood',3);ok(Crafting.count(c,'raw-wood')===q-3&&box.contents.find(r=>r.id==='raw-wood').quantity===3,'Store transfers exact resource quantity');Camping.transfer(box,'take','raw-wood',2);ok(Crafting.count(c,'raw-wood')===q-1,'Retrieve transfers exact quantity');throws(()=>Camping.pack([box]),'Non-empty storage box cannot be packed');const sword=c.inventoryItems.find(r=>r.id==='weapon-longsword');Camping.transfer(box,'store',sword.id,1);ok(c.primaryWeapon==='unarmed'&&!box.contents.find(r=>r.id===sword.id).equipped,'Storing equipped weapon unequips it');Camping.transfer(box,'take',sword.id,1);ok(c.inventoryItems.some(r=>r.id===sword.id),'Stored weapon returns with metadata');
  player.x+=100;player.center.x+=100;throws(()=>Camping.transfer(box,'take','raw-wood',1),'Remote storage access rejected');placeBy(box);
  const saved=JSON.parse(JSON.stringify(gameUI.buildSavePayload()));ok(saved.character.crafting.world.camps.deployed.find(o=>o.kind==='storage').contents.length>0,'Stored items persist in save payload');
  const occupied=worldCrafting.smith;Camping.begin('gear-tent');player.center={x:occupied.x-40,y:occupied.y};player.facing='right';player.x=player.center.x-player.width/2;player.y=player.center.y-player.height/2;const count=Crafting.count(c,'gear-tent'); // use a solid station to ensure placement rejection
  const station=worldCrafting.objects.find(o=>o.id==='public-forge');player.center={x:station.x-40,y:station.y};player.x=player.center.x-player.width/2;player.y=player.center.y-player.height/2;throws(()=>Camping.deploy(),'Occupied placement rejected');ok(Crafting.count(c,'gear-tent')===count,'Failed placement does not consume inventory');Camping.cancel();ok(Crafting.count(c,'gear-tent')===count,'Cancel placement preserves inventory');
  for(const[id,kind]of Object.entries(CAMP_ITEMS).map(([id,info])=>[id,info.kind])){
   Camping.begin(id);let valid;for(const tile of worldCrafting.tiles.filter(t=>t.d>10&&t.d<80)){const target={x:tile.x*16+8,y:tile.y*16+8};const center={x:target.x-40,y:target.y};const feet={x:center.x-player.width/2,y:center.y-player.height/2,width:player.width,height:player.height};const extra=Camping.objects().map(o=>Camping.footprint(o.kind,o.x,o.y));if(Camping.free(kind,target.x,target.y,extra)&&!collisionBlocks.concat(worldCrafting.getCollisionBlocks()).some(b=>Camping.overlap(feet,b))){valid={target,center};break;}}
   if(!valid)throw Error('No deployment location');player.center=valid.center;player.x=valid.center.x-player.width/2;player.y=valid.center.y-player.height/2;player.facing='right';Camping.deploy();const deployed=Camping.objects().at(-1);ok(deployed.kind===kind&&!Crafting.count(c,id),`${kind} deploys as map object and consumes item`);placeBy(deployed);Camping.pack([deployed]);ok(Crafting.count(c,id)===1&&!Camping.objects().some(o=>o.id===deployed.id),`${kind} packs back into inventory without duplication`);
  }
  const record={id:'crafted-storage-test',name:'Fine test sword',quantity:1,baseWeapon:'longsword',weaponId:'crafted-storage-test',material:'carburized',quality:'Fine',durability:6,improvements:['attack'],equipped:false};c.inventoryItems.push(record);Crafting.init(c);placeBy(box);Camping.transfer(box,'store',record.id,1);Camping.transfer(box,'take',record.id,1);ok(c.inventoryItems.find(r=>r.id===record.id).durability===6&&MELEE_WEAPONS[record.id].craftRecordId===record.id,'Crafted quality, durability and registry survive storage');
  const clone=JSON.parse(JSON.stringify(c)),stored=clone.crafting.world.camps.deployed.find(o=>o.id===box.id);ok(stored.contents.find(r=>r.id==='raw-wood').quantity===1,'Storage survives JSON round trip');
  const basePool=c.reflex+(c.proficiencies.longsword||0)-(c.armor.poolPenalty||0);gameUI.recalculateEquippedPools(c);ok(c.combatPools.longsword===Math.max(1,basePool-InventoryLoad.stats(c).cpPenalty),'Bulk penalty reaches combat pools');const oldMove=player.velocity;keys.d.pressed=true;player.handleInput(keys);keys.d.pressed=false;ok(player.velocity.x<150&&player.velocity.x>0,'Bulk slows actual map movement');player.velocity={x:0,y:0};
  const normal=c.conditions.fatigue,interval=InventoryLoad.stats(c).fatigueInterval;worldCrafting.state().travelFatigue=interval*1200-1;worldCrafting.update(1);ok(c.conditions.fatigue===normal+1,'Load-sensitive travel fatigue is applied');c.conditions.fatigue=0;
  return out;
 });console.log(checks.join('\n'));
 await page.evaluate(()=>{const box=Camping.objects().find(o=>o.kind==='storage');for(const[dx,dy]of[[20,0],[-20,0],[0,20],[0,-20]]){player.x=box.x+dx-player.width/2;player.y=box.y+dy-player.height/2;player.center={x:player.x+player.width/2,y:player.y+player.height/2};worldCrafting.update();if(worldCrafting.nearby()?.id===box.id)break;}});await page.keyboard.press('e');assert(await page.getByRole('dialog',{name:'Camp Storage'}).isVisible());await page.getByRole('combobox',{name:'Store carried items',exact:true}).selectOption('gear-tent');await page.getByRole('button',{name:'Store',exact:true}).click();await page.getByRole('combobox',{name:'Retrieve stored items',exact:true}).selectOption('gear-tent');await page.getByRole('button',{name:'Retrieve',exact:true}).click();await page.getByRole('button',{name:'Return to the world',exact:true}).click();
 const pixelChanges=await page.evaluate(async()=>{await worldCrafting.craftSprite.decode();const cv=document.createElement('canvas');cv.width=100;cv.height=100;const ctx=cv.getContext('2d');ctx.imageSmoothingEnabled=false;return [0,1,2,3,4].map(index=>{const snap=time=>{ctx.clearRect(0,0,100,100);ctx.save();ctx.translate(50,65);worldCrafting.drawFireStation(ctx,index,0,4,35,time);ctx.restore();return Array.from(ctx.getImageData(0,0,100,100).data);};const a=snap(0),b=snap(600);return a.filter((v,i)=>Math.abs(v-b[i])>2).length;});});assert(pixelChanges.every(n=>n>10),'All five fire station sprites animate');
 await page.evaluate(()=>{const f=worldCrafting.fire;player.x=f.x+20-player.width/2;player.y=f.y+8-player.height/2;player.center={x:player.x+player.width/2,y:player.y+player.height/2};worldCrafting.update();});await page.waitForTimeout(250);await page.screenshot({path:path.join(artifacts,'campsite-storage-and-fire.png')});
 const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(process.env.TEST_GAME_URL||'http://127.0.0.1:8766');await mobile.locator('#begin-game').tap();await mobile.locator('#equipment-item').selectOption('weapon-longsword');await mobile.locator('#equipment-add').tap();await mobile.locator('#finish-character').tap();await mobile.evaluate(()=>{battleSystem.nextEncounterDistance=1e9;gameUI.character.wealthTotal=1000;Camping.buy('gear-tent');});await mobile.locator('#touch-select').tap();await mobile.locator('#mobile-sheet-section').selectOption('inventory');await mobile.locator('.inventory-action-row').filter({hasText:'Two-person tent'}).getByRole('button',{name:'Deploy',exact:true}).tap();assert(await mobile.locator('.camp-placement-bar').isVisible());assert(!await mobile.locator('#touch-character').isDisabled());await mobile.locator('#touch-character').tap();assert(!await mobile.locator('.camp-placement-bar').isVisible());assert.equal(await mobile.evaluate(()=>Crafting.count(gameUI.character,'gear-tent')),1);
 await mobile.evaluate(()=>{const box=Camping.objects().find(o=>o.kind==='storage');for(const[dx,dy]of[[20,0],[-20,0],[0,20],[0,-20]]){player.x=box.x+dx-player.width/2;player.y=box.y+dy-player.height/2;player.center={x:player.x+player.width/2,y:player.y+player.height/2};worldCrafting.update();if(worldCrafting.nearby()?.id===box.id)break;}});await mobile.locator('#touch-interact').tap();assert(await mobile.getByRole('dialog',{name:'Camp Storage'}).isVisible());await mobile.screenshot({path:path.join(artifacts,'mobile-camp-storage.png'),scale:'css'});await mobile.locator('#touch-character').tap();assert(!await mobile.getByRole('dialog',{name:'Camp Storage'}).isVisible());assert.equal(errors.length,0,JSON.stringify(errors));console.log('Native storage UI, mobile deployment/back and storage controls, all burning station animations and no script/asset errors passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
